### ISSUE TITLE
[Design kit]: add footer

### ISSUE THREAD

**Issue by jeffchew** [jeffchew/test-repo#1093]
_Olivia-Flory created the following on Sep 26:_  

 ### User story
As a designer, I need access to visual design symbols of the new footer, so I can align my designs to the new standard.

### Notes
- Designers need to use the new footer in their designs so they don't confuse the developers with the northstar footer
- we need to include the footer in a design kit 

#### Outstanding questions
- should it be included in the Expressive design kit?
- should the footer be in a IBM.com library design kit?
- is any of it customizable?

### Tasks
- [ ] identify which pieces of the footer are customizable
- [ ] figure out symbol structure
- [ ] cover all breakpoints
- [ ] cover all variations
- [ ] add symbols to design kit

### Acceptance criteria
- [ ] Symbols match design and code specifications
- [ ] Design reviewed by Wonil 
- [ ] Design approved Wonil  

_Original issue: https://github.ibm.com/webstandards/digital-design/issues/1778_
