### ISSUE TITLE
Document coding style across dotcom

### ISSUE THREAD

**Issue by jeffchew** [jeffchew/test-repo#1442]
_vladislav-saling created the following on Oct 09:_  

 As a contributor I need to understand y'alls coding style so I can focus my attention more towards the problem I'm solving

We basically need a set of rules or guidelines used when writing code. We should automate as much of this as possible https://github.com/jeffchew/test-repo/issues/1442, but anything that can't be automated should live in a `STYLE_GUIDE` of sorts. It doesn't have to be anything extensive, but we should have a point of view as a team on how our code should be laid out for consistency sake. This will help set expectations, and speed up the contribution process.

### Resources for reference
 - [Google Styleguides](http://google.github.io/styleguide/)
 - [Carbon's Coding Style](https://github.com/IBM/carbon-components/blob/master/.github/CONTRIBUTING.md#coding-style)

### Acceptance criteria
- [ ] The file is referenced where appropriate, so users can navigate and find it.
- [ ] A `CODING_STYLE` file exists for [v18](https://github.ibm.com/webstandards/v18) within `.github` folder.
- [ ] A `CODING_STYLE` file exists for [v18-starter-kit](https://github.ibm.com/webstandards/v18-starter-kit) within `.github` folder.
- [ ] A `CODING_STYLE` file exists for [v19a](https://github.ibm.com/webstandards/v19a) within `.github` folder.
- [ ] A `CODING_STYLE` file exists for [patterns](https://github.ibm.com/webstandards/patterns) within `.github` folder.
- [ ] A `CODING_STYLE` file exists for [digital-design](https://github.ibm.com/webstandards/digital-design) within `.github` folder.
- [ ] A `CODING_STYLE` file exists for [carbon-integration-poc](https://github.ibm.com/webstandards/carbon-integration-poc) within `.github` folder.
- [ ] A `CODING_STYLE` file exists for [northstar-external-website](https://github.ibm.com/webstandards/northstar-external-website) within `.github` folder.
- [ ] A `CODING_STYLE` file exists for [IBM/carbon-addons-dotcom](https://github.com/IBM/carbon-addons-dotcom) within `.github` folder.
- [ ] [TBD: https://github.com/jeffchew/test-repo/issues/1442] A `CODING_STYLE` file exists for [IBM/dotcom-services](https://github.com/IBM/dotcom-services) within `.github` folder.
- [ ] [TBD: https://github.com/jeffchew/test-repo/issues/1442] A `CODING_STYLE` file exists for [IBM/dotcom-bundles](https://github.com/IBM/dotcom-website) within `.github` folder.
- [ ] [TBD: https://github.com/jeffchew/test-repo/issues/1442] A `CODING_STYLE` file exists for [IBM/dotcom-website](https://github.com/IBM/dotcom-website) within `.github` folder.

### Notes
 - Filename above is not super important compared to files like `LICENSE.md`
 - As great as it would be, codebases like [v18](https://github.ibm.com/webstandards/v18), and [v19a](https://github.ibm.com/webstandards/v19a) might be a lost cause for this issue creating too much overhead to implement. We can discuss this further though.

 

_Original issue: https://github.ibm.com/webstandards/digital-design/issues/224_

**Comment by jeffchew** [comment]
_On Apr 25, Lisa-Lurie commented:_
@vladislav-saling Can this be replaced/ closed because I have a Contribution Guidelines for Developers issue.

**Comment by jeffchew** [comment]
_On Apr 25, james-dow commented:_
@Lisa-Lurie I think this might could be re-worded, and I'll try to do that, but I think this is a little more specific. This is talking almost more about a style-guide which would be part of the contribution guidelines in some shape or form.

**Comment by jeffchew** [comment]
_On Apr 26, Lisa-Lurie commented:_
@james-dow Yes, take a whack at editing this. Also I think there is another issue, do a filter with guidelines. And yes, let's base it on Carbon! 
https://github.com/IBM/carbon-addons-dotcom/blob/master/.github/CONTRIBUTING.md

**Comment by jeffchew** [comment]
_On May 31, hahnrob commented:_
Jeff will talk to the development team to determine how this issue should be handled.  Target to make this decision is Friday, June 7.

**Comment by jeffchew** [comment]
_On Jun 07, Jeff-Chew commented:_
We're going to backlog this for now until we have a more stood up architecture with the newer dotcom. We can round back to this once that's been more crystalized.
