### ISSUE TITLE
Cupcake website page creation - Resources category

### ISSUE THREAD

**Issue by jeffchew** [jeffchew/test-repo#1733]
_chsanche created the following on Sep 24:_  

 

#### User Story

> As an IBM.com page creator

> I need to: know where to find resources

> so that I can: do my day to day work efficiently.

#### Additional information
- Cupcake website page development priority can be viewed via https://github.com/jeffchew/test-repo/issues/1733.
- The Resources page on the Carbon Design website can be viewed [here](https://www.carbondesignsystem.com/resources)
- We are going to combine all the resources into one page for the Cupcake version.
![Screen Shot 2019-09-24 at 1.33.25 PM.png](https://zenhub.ibm.com/images/569d5727c35226c2f582fbc9/a2fc5ae7-3e4c-4061-ba5b-e7769e9cfce1)

#### Task
- Collaborate with Wonil and Jeff for the content creation.

#### Acceptance criteria
- [x] Content and design created and reviewed with the stream lead, the developer and Wonil.
- [ ] Shared with the Carbon and IDL team for feedback.
- [ ] Content and design accepted by Wonil and Linda.
- [ ] Create the dev. issue for coding as the next step.

 

_Original issue: https://github.ibm.com/webstandards/digital-design/issues/1759_

**Comment by jeffchew** [comment]
_On Oct 01, chsanche commented:_
@Jeff-Chew @Benjamin-Hansen1 @Wonil-Suh1 

Please take a look at the content for the Resources page below and let me know if anything is missed.

![resources](https://media.github.ibm.com/user/5181/files/adbd7480-e44d-11e9-9045-bd076f76f233)
