### ISSUE TITLE
Design kit: add low contrast notifications and action variant

### ISSUE THREAD

**Issue by jeffchew** [jeffchew/test-repo#208]
### Add the low contrast notifications to the design kit

**Notes**
Carbon recently added the low contrast variants of the notification component into the system
![Screen Shot 2019-08-29 at 4.29.50 PM.png](https://zenhub.ibm.com/images/5bc1083e9c7a4b4b3d71ae3e/503fa778-9366-4f1c-ad0d-7a7ca1ded2fc)

They also added an 'action' variant to all notifications

**Tasks**
- [ ] add low contrast variants
- [ ] test low contrast variants
- [ ] add action variants
- [ ] test action variants
- [ ] restructure symbols to reflect updated groupings

**Acceptance criteria**
- [ ] all notification variants added to the kit
- [ ] symbols reflect the same structure as Carbon kit
