### ISSUE TITLE
Tech Assessment with 2019 DDS adopters

### ISSUE THREAD

**Issue by jeffchew** [jeffchew/test-repo#45]
_Lisa-Lurie created the following on May 21:_  

 Meetings with the individual DGC Teams, to understand their current environments, tech stacks, roadmap, etc. Also to speak about NPM adoption.

## Acceptance Criteria
- [ ] The architect has met with all of the adopter Technical Leads
- [ ] The technical details needed to design the Digital Design System has been documented for each adopter
- [ ] Technical status and gaps have also been documented for each adopter, to be used and input to build the IBM DDS roadmap 

 

_Original issue: https://github.ibm.com/webstandards/digital-design/issues/849_
