### ISSUE TITLE
Design assessment with 2019 DDS adopters

### ISSUE THREAD

**Issue by jeffchew** [jeffchew/test-repo#60]
_hahnrob created the following on Jun 05:_  

 Meetings with the individual DGC Teams, to understand their current design system

## Acceptance Criteria
- [ ] The IBM DDS team has met with all of the adopter Design Leads
- [ ] The design details have been documented for each adopter
- [ ] Design status and gaps have also been documented for each adopter, to be used and input to build the IBM DDS roadmap  

_Original issue: https://github.ibm.com/webstandards/digital-design/issues/949_
