### ISSUE TITLE
Design the new Block Link component

### ISSUE THREAD

**Issue by jeffchew** [jeffchew/test-repo#81]
_Wonil-Suh1 created the following on Jun 23:_  

 

As a IBM dot com user, I need a way to understand and identify the right item from a long list of links on a page, such as the search result page.

#### Additional information
In 2019, this is one of the main components used by the Product Discovery team. They just started their redesign effort - this work will be done in collaboration with them - they will do the research and propose UX, and visual design, we will co-design with them when necessary, and/or approve their design.
 - The priority is documented in the component [Airtable](https://airtable.com/tblYos5iDYwTP6MCK/viw85GYbUVISjrXj9?blocks=hide)
 - Assigned priority:  https://github.com/jeffchew/test-repo/issues/81

#### Tasks
- [ ] Meet with Product Discovery team to discuss timeline and collaboration model
- [ ] Meet establish testing plans

#### Acceptance criteria
- [ ] New design have been created
- [ ] New design has been accepted by the Product Discovery team leadership (Dave McDuff)
- [ ] Shared on Wake for feedback
- [ ] Shared with IDL for feedback
- [ ] Approved by DGC design leadership (Wonil Suh, Charlie Douglas, & Elliott Trice)
 

_Original issue: https://github.ibm.com/webstandards/digital-design/issues/1095_
